2020-01-05 18:32:34,547 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:32]
2020-01-05 18:34:12,439 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:32]
2020-01-05 18:34:41,485 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:32]
2020-01-05 18:35:00,294 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:32]
2020-01-05 18:35:33,559 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:32]
2020-01-05 18:35:45,082 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:32]
2020-01-05 18:35:57,138 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:32]
2020-01-05 18:36:52,352 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:32]
2020-01-05 18:37:02,364 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:32]
2020-01-05 18:37:30,015 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:32]
2020-01-05 19:34:07,328 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:32]
2020-01-06 13:45:29,480 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:32]
2020-01-06 18:53:21,825 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:32]
2020-01-06 18:53:37,586 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:32]
2020-01-06 18:59:20,060 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:32]
2020-01-06 18:59:52,403 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:32]
2020-01-06 19:00:26,291 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:32]
2020-01-06 19:01:02,928 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:32]
2020-01-06 19:01:43,844 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:32]
2020-01-06 19:01:47,529 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:32]
2020-01-06 19:02:26,274 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:32]
2020-01-06 19:02:48,042 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:32]
2020-01-06 19:03:15,219 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:32]
2020-01-06 19:03:31,702 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:32]
2020-01-07 19:50:14,782 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:32]
2020-01-07 19:53:12,864 ERROR: Exception on / [GET] [in /Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/application/routes.py", line 69, in index
    return render_template('index.html', title='Home', posts=posts)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/application/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/application/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/application/templates/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/application/templates/index.html", line 9, in block "app_content"
    <button onclick="window.location.href = '{{ url_for('createdataset') }}'" type="button" class="btn btn-primary">New session</button>
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'createdataset'. Did you mean 'createSession' instead?
2020-01-07 19:53:53,392 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:32]
2020-01-07 19:53:55,068 ERROR: Exception on / [GET] [in /Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/application/routes.py", line 69, in index
    return render_template('index.html', title='Home', posts=posts)
NameError: name 'posts' is not defined
2020-01-07 19:54:11,626 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:32]
2020-01-07 20:03:56,333 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:32]
